version: '3.8'

services:
  # --- 1. Uygulama (Flask) ---
  app:
    build: .
    container_name: ekosan_app_v2
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - SECRET_KEY=b7f43a2d1e8c9b0a5f6d7e8c9b0a1b2c3d4e5f6
      - DATABASE_URL=postgresql://ekosan_admin_user:Ekosan.621313.!!@db:5432/ekosandb
      - UPLOAD_PATH=/app/static/uploads
    depends_on:
      - db
    networks:
      - ekosan_net
    volumes:
      - app_uploads:/app/static/uploads
    restart: unless-stopped
    ports:
      - "5005:5000"

  # --- 2. Veritabanı (Postgres) ---
  db:
    image: postgres:15-alpine
    container_name: ekosan_db_v2
    environment:
      POSTGRES_USER: ekosan_admin_user
      POSTGRES_PASSWORD: Ekosan.621313.!!
      POSTGRES_DB: ekosandb
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - ekosan_net
    restart: unless-stopped

  # --- 3. Nginx Proxy Manager (Domain Yönetimi) ---
  nginx_proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: ekosan_npm
    restart: unless-stopped
    ports:
      - '80:80'    # HTTP Trafiği
      - '81:81'    # Yönetim Paneli (Admin UI)
      - '443:443'  # HTTPS (SSL) Trafiği
    volumes:
      - ./npm_data:/data              # Ayarların kaybolmaması için
      - ./npm_letsencrypt:/etc/letsencrypt  # SSL sertifikalarının saklanması için
    networks:
      - ekosan_net

# --- Kalıcı Depolama Alanları ---
volumes:
  pg_data:
  app_uploads:

# --- Ağ Ayarları ---
networks:
  ekosan_net:
    driver: bridge